"""add quiz attempt submission fields

Revision ID: 0cd052074b0e
Revises: 9e9ef9fd394a
Create Date: 2026-07-21 10:49:58.510568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd052074b0e'
down_revision: Union[str, None] = '9e9ef9fd394a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('answers_json', sa.JSON(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'submitted_at')
    op.drop_column('quiz_attempts', 'score')
    op.drop_column('quiz_attempts', 'answers_json')
    # ### end Alembic commands ###
