"""add sections table

Revision ID: 7ae9a8fc4dd5
Revises: f7c5725480de
Create Date: 2026-07-22 15:29:08.007761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae9a8fc4dd5'
down_revision: Union[str, None] = 'f7c5725480de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite can't ALTER a constraint onto an existing table directly —
    # batch mode does the copy-and-move rebuild it needs under the hood.
    with op.batch_alter_table('quiz_attempts') as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_attempts_section_id_sections', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts') as batch_op:
        batch_op.drop_constraint('fk_quiz_attempts_section_id_sections', type_='foreignkey')
        batch_op.drop_column('section_id')
    op.drop_table('sections')
    # ### end Alembic commands ###
